In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(Y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6 , activation = 'relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

In [16]:
ann.compile(optimizer = 'adam',loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
ann.fit(X_train,Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7996 - accuracy: 0.5157
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5943 - accuracy: 0.7782
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4904 - accuracy: 0.7985
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4485 - accuracy: 0.8075
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8149
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8201
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 0.8298
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3783 - accuracy: 0.8371
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3717 - accuracy: 0.8420
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3681 - accura

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

[[0.02382708]]


In [19]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
accuracy_score(Y_test,Y_pred)

[[1531   64]
 [ 205  200]]


0.8655